# Generated by Django 2.2.5 on 2020-02-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller_1', '0002_auto_20200213_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
