# Generated by Django 2.2.5 on 2020-02-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller_1', '0003_auto_20200213_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
