# Generated by Django 2.2.5 on 2020-03-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller_1', '0004_auto_20200213_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=20)),
                ('artist_id', models.CharField(max_length=20)),
                ('user_rating', models.IntegerField(null=True)),
                ('global_rating', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reproduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('song_name', models.CharField(max_length=20)),
                ('song_id', models.CharField(max_length=20)),
                ('date', models.DateTimeField(null=True)),
                ('artist_name', models.CharField(max_length=20)),
                ('artist_id', models.CharField(max_length=20)),
            ],
        ),
    ]
