# Generated by Django 2.2.5 on 2020-03-08 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller_1', '0005_artista_reproduccion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artista',
            new_name='Artist',
        ),
        migrations.RenameModel(
            old_name='Reproduccion',
            new_name='Reproduction',
        ),
    ]
