# Generated by Django 2.2.5 on 2020-03-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller_1', '0006_auto_20200308_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('numero_artistas', models.IntegerField()),
                ('numero_reproducciones', models.IntegerField()),
            ],
        ),
    ]
