# Generated by Django 2.2.5 on 2020-03-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller_1', '0007_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=20)),
                ('artist_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('rating_lineal', models.IntegerField(null=True)),
            ],
        ),
    ]
