# Generated by Django 2.2.5 on 2020-03-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller_1', '0009_auto_20200311_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingTemporal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id_pos', models.IntegerField(null=20)),
                ('user_id_pos', models.IntegerField(null=20)),
                ('rating_lineal', models.IntegerField(null=True)),
            ],
        ),
    ]
