# Generated by Django 2.2.5 on 2020-05-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40)),
                ('business_id', models.CharField(max_length=40)),
                ('categories', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('is_open', models.IntegerField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('name', models.CharField(max_length=40)),
                ('postal_code', models.CharField(max_length=40)),
                ('review_count', models.IntegerField(null=True)),
                ('stars', models.FloatField(null=True)),
                ('state', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40)),
                ('business_id', models.CharField(max_length=40)),
                ('last_review', models.DateField(null=True)),
                ('year_review', models.PositiveIntegerField(null=True)),
                ('stars', models.PositiveIntegerField(null=True)),
                ('attractive_count', models.PositiveIntegerField(null=True)),
                ('review_id', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_stars', models.FloatField(null=True)),
                ('compliment_cool', models.IntegerField(null=True)),
                ('compliment_cute', models.IntegerField(null=True)),
                ('compliment_funny', models.IntegerField(null=True)),
                ('compliment_hot', models.IntegerField(null=True)),
                ('compliment_list', models.IntegerField(null=True)),
                ('compliment_more', models.IntegerField(null=True)),
                ('compliment_note', models.IntegerField(null=True)),
                ('compliment_photos', models.IntegerField(null=True)),
                ('compliment_plain', models.IntegerField(null=True)),
                ('compliment_profile', models.IntegerField(null=True)),
                ('compliment_writer', models.IntegerField(null=True)),
                ('cool', models.IntegerField(null=True)),
                ('fans', models.IntegerField(null=True)),
                ('funny', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=40)),
                ('review_count', models.IntegerField(null=True)),
                ('useful', models.IntegerField(null=True)),
                ('user_id', models.CharField(max_length=40)),
                ('yelping_since', models.DateField(null=True)),
            ],
        ),
    ]
