# Generated by Django 2.2.5 on 2020-05-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='categories',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
