# Generated by Django 2.2.5 on 2020-05-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller_2', '0002_auto_20200502_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='last_review',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='yelping_since',
            field=models.DateTimeField(null=True),
        ),
    ]
